import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  FormOutline,
  DashboardOutline,
  PhoneFill,
  MailFill,
  LoginOutline,
  HomeFill,
  CalendarFill,
  ReadFill,
  ScheduleFill,
  FileSearchOutline,
  IdcardFill,
  InfoCircleFill,
  UserOutline,
  SearchOutline,
  SettingOutline,
  EyeInvisibleOutline,
} from '@ant-design/icons-angular/icons';

export const icons = [
  MenuFoldOutline,
  MenuUnfoldOutline,
  DashboardOutline,
  FormOutline,
  PhoneFill,
  MailFill,
  LoginOutline,
  PhoneFill,
  HomeFill,
  CalendarFill,
  ReadFill,
  ScheduleFill,
  FileSearchOutline,
  IdcardFill,
  InfoCircleFill,
  UserOutline,
  SearchOutline,
  SettingOutline,
  EyeInvisibleOutline,
];
